app/models.py
from flask_login import UserMixin
from datetime import datetime
from werkzeug.security import generate_password_hash, check_password_hash
from app import db, login_manager

@login_manager.user_loader
def load_user(id):
    return User.query.get(id)


class User(UserMixin,db.Model):
    user_id = db.Column(db.Integer, primary_key = True)
    first_name = db.Column(db.String(30))
    last_name = db.Column(db.String(30))
    username = db.Column(db.String(100), nullable = False, unique = True)
    email = db.Column(db.String(180), nullable = False, unique = True)
    password_hash = db.Column(db.String(), nullable = False)
    recipes = db.relationship('Recipe', backref = 'author', lazy=True)


    def to_dict(self):
        return {
            'first_name': self.first_name,     
            'last_name': self.last_name,
            'email': self.email,
            'username': self.username,
            'recipes': [{
            'body':post.body, 
            'timestamp':post.timestamp
        } for post in self.posts ]
        }


    def __repr__(self):
        return f'<User: {self.username}'
    
    def commit(self):
        db.session.add(self)
        db.session.commit()

    def from_dict(self, user_obj):
        for attribute, value in user_obj.items():
            setattr(self, attribute, value)

    def get_id(self):
        return str(self.user_id)

    def hash_password(self,password):
        self.password_hash = generate_password_hash(password)

    def check_password(self,password):
        return check_password_hash(self.password_hash, password)
    
class Recipe(db.Model):
    recipe_id = db.Column(db.Integer, primary_key = True)
    body = db.Column(db.String(), nullable = False)
    timestamp = db.Column(db.DateTime, default=datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey('user.user_id'), nullable= False)

    def __repr__(self):
        return f'<Recipe: {self.body}>'
    

    def commit(self):
        db.session.add(self)
        db.session.commit()

app/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, EqualTo

class LoginForm(FlaskForm):
    email = StringField('Email:', validators=[ DataRequired()])
    password = PasswordField('Password:', validators=[ DataRequired()])
    submit = SubmitField('Sign In')

class SignUpForm(FlaskForm):
    first_name = StringField('First Name: ')
    last_name = StringField('Last Name: ')
    username = StringField('Username:',validators=[ DataRequired() ])
    email = StringField('Email:', validators=[ DataRequired() ])
    password = PasswordField('Password:', validators=[ DataRequired() ])
    verify_password = PasswordField('Confirm Password:', validators=[ DataRequired(), EqualTo('password') ])
    submit = SubmitField('Sign Up')

class RecipeForm(FlaskForm):
    body = StringField('Post a recipe:', validators=[DataRequired()])
    submit = SubmitField('Post')


class RecipeSearchForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    submit = SubmitField('Search User')


    

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager
from flask_cors import CORS
from Config import Config
from flask_jwt_extended import JWTManager


app = Flask(__name__)
app.config.from_object(Config)
db = SQLAlchemy(app)
migrate = Migrate(app, db)
jwt = JWTManager(app)
CORS(app)

login_manager = LoginManager(app)
login_manager.login_view = 'auth.sign_in'
login_manager.login_message = 'Please log in before proceeding'
login_manager.login_message_category = 'warning'

from app.blueprints.social import bp as social
app.register_blueprint(social)
from app.blueprints.auth import bp as auth
app.register_blueprint(auth)
from app.blueprints.main import bp as main
app.register_blueprint(main)



#Must be at bottom of file prevent circular import
from app import models

app/blueprints/api/__init__.py
from flask import Blueprint

bp = Blueprint('api', __name__, url_prefix='/api')

from . import auth_routes, social_routes

app/blueprints/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from . import routes

app/blueprints/main/routes.py
from flask import render_template, g
from . import bp as main


@main.route('/')
def home_page():
    recipe_posts = {
        'titles': {
            'pasta':['We are making a pasta'],
            'sauce': ['make a pasta sauce']
        },
        'foods':{ food:[f'as item {num}'] for num, food in enumerate(['tomato','basil','garlic','veggie'])}
    }
    print(recipe_posts['foods'])
    return render_template('index.jinja', titles=recipe_posts['titles'], foods=recipe_posts['foods'], title='Pinch of Yum')

@main.route('/recipes')
def recipe():
    recipe = {
        'title': 'Pasta Carbonara',
        'ingredients': ['pasta', 'bacon', 'eggs', 'cheese'],
        'instructions': [ 'Cook pasta','fry bacon', 'beat eggs', 'mix all together', 'add cheese', 'enjoy!']
    }
    return render_template('recipe.jinja', recipe=recipe)

app/blueprints/social/__init__.py
from flask import Blueprint

bp = Blueprint('social', __name__, url_prefix='/social')

from . import routes

app/blueprints/social/routes.py
from flask import render_template, redirect, flash, url_for, g 
from flask_login import current_user, login_required
from app import app
from app.forms import RecipeForm, RecipeSearchForm
from app.models import User, Recipe
from . import bp


@app.before_request
def before_request():
    g.recipe_search_form = RecipeSearchForm()
    g.recipe_form = RecipeForm()


@bp.post('/post')
def post():
    if g.recipe_form.validate_on_submit():
        post = Recipe(body=g.recipe_form.body.data, user_id = current_user.user_id)
        post.commit()
        flash('Recipe posted!', category='success')
    return redirect(url_for('social.profile', username = current_user.username))

@bp.route('/profile/<username>')
@login_required
def profile(username):
    user = User.query.filter_by(username=username).first()
    if user:
        recipes = user.recipes
        return render_template('profile.jinja', username=username, recipes=recipes)
    else:
        flash(f'User: {username} is not valid!', category='warning')
        return redirect(url_for('main.home'))
    
@bp.post('user-search')
def user_search():
    return redirect(url_for('social.profile', username=g.recipe_search_form.username.data))

app/routes.py
from flask import render_template, flash, redirect
from app import app
from app.forms import LoginForm, SignUpForm
from app.models import User

@app.route('/')
def home_page():
    recipe_posts = {
        'titles': {
            'pasta':['We are making a pasta'],
            'sauce': ['make a pasta sauce']
        },
        'foods':{ food:[f'as item {num}'] for num, food in enumerate(['tomato','basil','garlic','veggie'])}
    }
    print(recipe_posts['foods'])
    return render_template('index.jinja', titles=recipe_posts['titles'], foods=recipe_posts['foods'], title='Pinch of Yum')


@app.route('/recipes')
def recipe():
    recipe = {
        'title': 'Pasta Carbonara',
        'ingredients': ['pasta', 'bacon', 'eggs', 'cheese'],
        'instructions': [ 'Cook pasta','fry bacon', 'beat eggs', 'mix all together', 'add cheese', 'enjoy!']
    }
    return render_template('recipe.jinja', recipe=recipe)


@app.route('/signin', methods=['Get', 'POST'])
def sign_in():
    signin_form = LoginForm()
    if signin_form.validate_on_submit():
        email = signin_form.email.data
        user = User.query.filter_by(email=email).first()
        if user and user.check_password(signin_form.password.data):
            flash(f'{signin_form.email.data} successfully logged in!' ,category='success')
            return redirect('/')
        else:
            flash(f'Invalid User Info, Please try again!', category='alert')
    return render_template('signin.jinja', form=signin_form)

@app.route('/signup', methods=['Get', 'POST'])
def sign_up():
    signup_form = SignUpForm()
    if signup_form.validate_on_submit():
        first_name = signup_form.first_name.data
        last_name = signup_form.last_name.data
        username = signup_form.username.data
        email = signup_form.email.data
        try:
            user = User(first_name=first_name, last_name=last_name, username=username, email=email)
            user.hash_password(signup_form.password.data)
            user.commit()
            flash(f'{first_name if first_name else username} is registered', category='success')
            return redirect('/')
        except:
            flash(f'Username or Email is already taken. Please try again!', category='alert')
    return render_template('signup.jinja', form=signup_form)

app/templates/base.jinja
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>
    {% if title %}
      {{ title }}
    {% else %}
      Pinch Of Yum
    {% endif %}
  </title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" defer></script>
</head>
<body class="container">
  {% include "navbar.jinja" %}
  {% with messages =  get_flashed_messages(with_categories=true) %}
    {% for category, message in messages %}
      <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
        <strong>{{ category.title() }}</strong> {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    {% endfor %}
  {% endwith %}
  {%if current_user.is_authenticated%}
    {{current_user.username}}
    {%include "post.jinja"%}
  {%endif%}
  {% block content %}{% endblock %}

</body>
</html>

app/templates/index.jinja
{% extends "base.jinja" %}
  
{% block content %}

  <p>These items are to be needed to make food. {{ titles['pasta'][0] }}</p>
  <p>We are going to add more items to {{ titles.sauce[0] }}</p>

  {% for food in foods %}
    <p>{{ food.title() }} is needed {{ foods[food][0] }}</p>
  {% endfor %}

{% endblock content %} 

app/templates/navbar.jinja
<nav class="navbar navbar-expand-lg bg-body-tertiary mb-4">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Pinch of Yum</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{{ url_for('main.home_page') }}">Home</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Recipes
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{{ url_for('main.recipe') }}">Pasta</a></li>
            <li><a class="dropdown-item" href="#">Random</a></li>
          </ul>
          </li>
          {% if current_user.is_authenticated %}
          <li class="nav-item">
          <a class="nav-link active" href="{{ url_for('social.profile', username=current_user.username) }}">My Page</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{{ url_for('auth.log_out') }}">Log out</a>
        </li>
        {%else%}
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('auth.sign_in') }}">Sign In</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('auth.sign_up') }}">Sign Up</a>
          {%endif%}
      </ul>
       <form class="d-flex" method="POST" action="{{ url_for('social.user_search') }}">
        {{ g.recipe_search_form.hidden_tag() }}
        {{ g.recipe_search_form.username() }}
        {{ g.recipe_search_form.submit() }}
      </form>
    </div>
  </div>
</nav>

app/templates/post.jinja
  <form action="{{ url_for('social.post') }}" method="POST">
    {{ g.recipe_form.hidden_tag() }}
    <span>{{ g.recipe_form.body() }}</span>
    <p>{{ g.recipe_form.submit() }}</p>
  </form>

app/templates/profile.jinja
{%extends "base.jinja"%}

{%block content%}

<h2>{{username}}</h2>
<main class = 'recipes'>
<ul>
    {% for post in recipes %}
    <li>{{post.body}} posted: {{post.timestamp}}</li>
    {%endfor%}
</ul>

</main>

{%endblock content%}

app/templates/recipe.jinja
{% extends "base.jinja" %}
{% block content %}
    <h2>{{ recipe.title }}</h2>

    <h3>Ingredients:</h3>
    <ul>
        {% for ingredient in recipe.ingredients %}
            <li>{{ ingredient }}</li>
        {% endfor %}
    </ul>
    <h3>Instructions:</h3>
    <ol>
        {% for instruction in recipe.instructions %}
        <li>{{ instruction }}</li>
        {%endfor%}
    </ol>

{% endblock content %} 

app/templates/signin.jinja
{% extends "base.jinja" %}
  
{% block content %}
<h3>Sign In</h3>

<form action="" method="POST" novalidate>
{{form.hidden_tag()}}

<p>{{form.email.label}}<br>
    {{form.email(size=32)}}
    {% for error in form.email.errors%}
    <span>{{error}}</span>
    {%endfor%}
</p>
<p>
{{form.password.label}}<br>
{{form.password(size=32)}}
{%for error in form.password.errors%}
<span>{{error}}</span>
{%endfor%}
</p>
<p>{{form.submit()}}</p>

</form>
{% endblock content %} 

app/templates/signup.jinja
{% extends "base.jinja" %}

{% block content %}
  <h3>Sign Up Here</h3>
  <form action="" method="POST" novalidate>
    {{ form.hidden_tag() }}
    <p>
      {{ form.first_name.label }}<br>
      {{ form.first_name(size=32) }}
    </p>
    <p>
      {{ form.last_name.label }}<br>
      {{ form.last_name(size=32) }}
    </p>
    <p>
      {{ form.username.label }}<br>
      {{ form.username(size=32) }}
      {% for error in form.username.errors %}
        <span>{{ error }}</span>
      {% endfor %}
    </p>
    <p>
      {{ form.email.label }}<br>
      {{ form.email(size=32) }}
      {% for error in form.email.errors %}
        <span>{{ error }}</span>
      {% endfor %}
    </p>
    <p>
      {{ form.password.label }}<br>
      {{ form.password(size=32) }}
      {% for error in form.password.errors %}
        <span>{{ error }}</span>
      {% endfor %}
    </p>
    <p>
      {{ form.verify_password.label }}<br>
      {{ form.verify_password(size=32) }}
      {% for error in form.verify_password.errors %}
        <span>{{ error }}</span>
      {% endfor %}
    </p>
    <p>{{ form.submit() }}</p>
    </form>
{% endblock content %}